export const BANK = [
  {
    n: 1,
    t: "Foundations of civil defense",
    q: "What is the definition of Civil Defense as a science?",
    o: [
      "Civil defense is the science of ensuring human safety and health and a system of measures prepared in advance for peacetime and wartime emergencies.",
      "A branch of military logistics studying how troops are deployed, supplied, and moved across terrain in wartime",
      "A field of urban planning focused only on building codes, construction permits, and municipal zoning regulations",
      "An academic discipline limited strictly to forecasting natural disasters using historical weather statistics",
    ],
    a: 0,
  },
  {
    n: 2,
    t: "Foundations of civil defense",
    q: "Which of the following is NOT one of the main objectives of civil defense?",
    o: [
      "Prevention of emergencies before they can ever happen at all, under any cost",
      "Minimization of harm and damage during an ongoing event or active incident",
      "Elimination of lasting consequences after an emergency has fully concluded",
      "Any objective other than: prevention of emergencies, minimization of damage, and elimination of consequences.",
    ],
    a: 3,
  },
  {
    n: 3,
    t: "Foundations of civil defense",
    q: "What is the definition of an Emergency situation?",
    o: [
      "A scheduled drill conducted purely to test institutional readiness and staff timing each calendar year",
      "An emergency situation is an event causing human casualties, environmental damage, material losses, and disruption of normal living conditions.",
      "A minor incident producing no lasting structural, social, or environmental impact on the wider community",
      "A temporary budget shortfall affecting local emergency service funding for one single fiscal quarter",
    ],
    a: 1,
  },
  {
    n: 4,
    t: "Foundations of civil defense",
    q: "What is the purpose of Recovery procedures?",
    o: [
      "To assign official blame for the disaster's underlying root cause and failures",
      "To permanently relocate all residents who were affected by the original event",
      "To restore normal life, rehabilitate services and facilities, and provide essential support after disasters.",
      "To document and process insurance claims for property damaged in the event",
    ],
    a: 2,
  },
  {
    n: 5,
    t: "Foundations of civil defense",
    q: "The first organization created regarding civil defense was established in 1931 by whom?",
    o: [
      "Georges Saint-Paul.",
      "Henry Dunant.",
      "Florence Nightingale.",
      "Jean Henry Pictet.",
    ],
    a: 0,
  },
  {
    n: 6,
    t: "Foundations of civil defense",
    q: "When is International Civil Defense Day celebrated?",
    o: ["February 14.", "April 22.", "June 5.", "March 1."],
    a: 3,
  },
  {
    n: 7,
    t: "Foundations of civil defense",
    q: "Which city hosted the 13th International Conference on Civil Defense in 2013?",
    o: ["Baku.", "Gabala.", "Ganja.", "Shaki."],
    a: 1,
  },
  {
    n: 8,
    t: "State Emergency System structure",
    q: "On what date was the President's Decree No.700 signed?",
    o: ["March 30, 1996.", "May 22, 2001.", "April 18, 1998.", "June 9, 2003."],
    a: 2,
  },
  {
    n: 9,
    t: "State Emergency System structure",
    q: "On what date was the State Emergency Situations System established?",
    o: ["April 30, 1992.", "May 15, 1994.", "June 3, 1996.", "July 21, 1999."],
    a: 0,
  },
  {
    n: 10,
    t: "State Emergency System structure",
    q: "At which three levels is the State Emergency Situations System managed?",
    o: [
      "Village council level, regional government level, and the national federal level overall",
      "Local police command level, military command structure level, and judiciary review level",
      "International coordination level, national government level, and individual household level",
      "Cabinet of Ministers level, city and district executive authorities level, national economy facilities level.",
    ],
    a: 3,
  },
  {
    n: 11,
    t: "State Emergency System structure",
    q: "Which operational mode works under normal industrial and safe conditions?",
    o: [
      "High Alert mode.",
      "Daily working mode.",
      "Emergency response mode.",
      "Full mobilization mode.",
    ],
    a: 1,
  },
  {
    n: 12,
    t: "State Emergency System structure",
    q: "When are operations strengthened under High Alert mode?",
    o: [
      "During routine annual safety inspections of nearby facilities",
      "Only during scheduled training exercises for newly hired staff",
      "When emergencies are likely in radioactive, chemical, biological, and hazardous conditions.",
      "When media outlets report unrelated public concerns or rumors",
    ],
    a: 2,
  },
  {
    n: 13,
    t: "State Emergency System structure",
    q: "Which Regional Center is located in Gabala and covers 10 districts?",
    o: [
      "North-West Regional Center.",
      "Mugan Regional Center.",
      "Ganja Regional Center.",
      "North Regional Center.",
    ],
    a: 0,
  },
  {
    n: 14,
    t: "State Emergency System structure",
    q: "Which districts are covered by the North Regional Center?",
    o: [
      "Salyan, Shirvan, Neftchala, Hajigabul, Sabirabad.",
      "Saatli, Bilasuvar, Imishli, Sabirabad, Salyan.",
      "Goychay, Agdash, Ujar, Zardab, Kurdamir.",
      "Khachmaz, Quba, Qusar, Shabran, Siyazan.",
    ],
    a: 3,
  },
  {
    n: 15,
    t: "State Emergency System structure",
    q: "In which city is the Ganja Regional Center located?",
    o: ["Baku.", "Ganja.", "Sumgait.", "Mingachevir."],
    a: 1,
  },
  {
    n: 16,
    t: "State Emergency System structure",
    q: "Which districts are covered by the Mugan Regional Center?",
    o: [
      "Khachmaz, Quba, Qusar, Shabran, Siyazan, and Gabala overall.",
      "Goranboy, Naftalan, Samukh, Tartar, and Barda districts.",
      "Salyan, Shirvan, Neftchala, Hajigabul, Sabirabad, Saatli, Bilasuvar, Imishli.",
      "Lankaran, Astara, Masalli, Jalilabad, and Yardimli zones.",
    ],
    a: 2,
  },
  {
    n: 17,
    t: "Commissions & headquarters",
    q: "What is one of the primary objectives of the Emergency Situations Commission of the Cabinet of Ministers?",
    o: [
      "To ensure constant readiness of management bodies and State System forces for emergencies and to coordinate prevention, rescue, and recovery activities.",
      "To approve the national annual budget allocations for every government ministry and agency each new fiscal year",
      "To oversee unrelated foreign trade negotiations and international tariff agreements signed on behalf of the state",
      "To manage routine municipal infrastructure construction projects that are unrelated to emergency response planning",
    ],
    a: 0,
  },
  {
    n: 18,
    t: "Commissions & headquarters",
    q: "Who leads the Emergency Situations Commissions at city and district levels?",
    o: [
      "The regional Chief of Police.",
      "The local Mayor's press secretary.",
      "The district Chief Engineer.",
      "First Deputy of the Executive Authority.",
    ],
    a: 3,
  },
  {
    n: 19,
    t: "Commissions & headquarters",
    q: "Who leads the Emergency Situations Commissions at national economy facilities?",
    o: [
      "First Deputy of the Executive Authority.",
      "Chief Engineer.",
      "The facility's HR director.",
      "The site's finance manager.",
    ],
    a: 1,
  },
  {
    n: 20,
    t: "Commissions & headquarters",
    q: "What is a main responsibility of the Civil Defense Headquarters during peacetime?",
    o: [
      "Direct combat deployment of military units in the field",
      "Issuing personal firearm licenses to ordinary citizens",
      "Preparation and analysis of civil defense plans.",
      "Managing day-to-day traffic enforcement in the district",
    ],
    a: 2,
  },
  {
    n: 21,
    t: "Commissions & headquarters",
    q: "What external communication action is the responsibility of the Civil Defense Headquarters during an emergency?",
    o: [
      "Notifying neighboring districts and facilities.",
      "Posting updates on personal social media accounts directly",
      "Contacting international news agencies before local ones",
      "Sending private memos to company shareholders only",
    ],
    a: 0,
  },
  {
    n: 22,
    t: "Commissions & headquarters",
    q: "Which is one of the Main Documents of the Civil Defense Headquarters?",
    o: [
      "Annual Tax Filing Report.",
      "Employee Vacation Schedule.",
      "Building Lease Agreement.",
      "Civil Defense Plan.",
    ],
    a: 3,
  },
  {
    n: 23,
    t: "Planning, exercises & training",
    q: "To whom is the Civil Defense Plan of the Republic of Azerbaijan submitted for approval?",
    o: [
      "The Speaker of the Milli Majlis legislative assembly",
      "President of the Republic of Azerbaijan.",
      "The Mayor of Baku city administration office",
      "The Chairman of the Supreme Court of Azerbaijan",
    ],
    a: 1,
  },
  {
    n: 24,
    t: "Planning, exercises & training",
    q: "Who develops and approves the Annual Civil Defense Measures Plan of the Republic of Azerbaijan?",
    o: [
      "Ministry of Internal Affairs of the Republic of Azerbaijan",
      "Ministry of Foreign Affairs of the Republic of Azerbaijan",
      "Ministry of Emergency Situations of the Republic of Azerbaijan.",
      "The State Statistics Committee of Azerbaijan",
    ],
    a: 2,
  },
  {
    n: 25,
    t: "Planning, exercises & training",
    q: "How often are civil defense exercises for leadership held?",
    o: [
      "Once a year.",
      "Once a month.",
      "Once every five years.",
      "Every six months.",
    ],
    a: 0,
  },
  {
    n: 26,
    t: "Planning, exercises & training",
    q: "Who participates in the annual civil defense exercise for leadership?",
    o: [
      "Only foreign diplomatic observers and visiting embassy staff members",
      "Solely private contractors and outside vendors hired for the event",
      "Only volunteer university student groups from nearby campuses",
      "Civil defense headquarters, service leadership, and non-militarized team leadership.",
    ],
    a: 3,
  },
  {
    n: 27,
    t: "Planning, exercises & training",
    q: "How often are warning assembly drills with non-militarized teams held?",
    o: [
      "Once a month.",
      "Twice a year.",
      "Once every three years.",
      "Four times a year.",
    ],
    a: 1,
  },
  {
    n: 28,
    t: "Planning, exercises & training",
    q: "How often are operational exercises for highly trained non-militarized teams held?",
    o: [
      "Twice a month.",
      "Once every decade.",
      "Once a year.",
      "Three times a year.",
    ],
    a: 2,
  },
  {
    n: 29,
    t: "Planning, exercises & training",
    q: "Under which ministry are leadership training and civil defense courses organized?",
    o: [
      "Ministry of Emergency Situations.",
      "Ministry of Education.",
      "Ministry of Internal Affairs.",
      "Ministry of Labor and Social Protection.",
    ],
    a: 0,
  },
  {
    n: 30,
    t: "Emergency classification",
    q: "Emergencies that can be predicted in advance and whose outcomes are known are classified as:",
    o: [
      "Unmanageable emergencies.",
      "Supernatural emergencies.",
      "Global emergencies.",
      "Ordinary emergencies.",
    ],
    a: 3,
  },
  {
    n: 31,
    t: "Emergency classification",
    q: "Emergencies that are difficult to predict but manageable are classified as:",
    o: [
      "Ordinary emergencies.",
      "Unexpected emergencies.",
      "Municipal emergencies.",
      "Socio-economic emergencies.",
    ],
    a: 1,
  },
  {
    n: 32,
    t: "Emergency classification",
    q: "What is the key characteristic of Unmanageable emergencies?",
    o: [
      "They never cause any casualties or material losses under any circumstances at all",
      "They resolve themselves naturally over time, without any outside intervention needed",
      "They are predictable but difficult to respond to and require long time and great effort to eliminate consequences.",
      "They only occur in remote and sparsely populated rural regions far from any city",
    ],
    a: 2,
  },
  {
    n: 33,
    t: "Emergency classification",
    q: "Supernatural emergencies are characterized by being:",
    o: [
      "Unpredictable and extremely difficult or impossible to respond to.",
      "Fully predictable and very easily resolved in practice",
      "Limited strictly to small indoor settings or rooms",
      "Resolved within a few short minutes of onset",
    ],
    a: 0,
  },
  {
    n: 34,
    t: "Emergency classification",
    q: "An emergency occurring within a neighborhood or village is categorized by scope as:",
    o: [
      "Regional emergency.",
      "National emergency.",
      "Global emergency.",
      "Municipal emergency.",
    ],
    a: 3,
  },
  {
    n: 35,
    t: "Emergency classification",
    q: "Global emergencies by scope are defined as emergencies that:",
    o: [
      "Stay confined to a single small village or town",
      "Occur in at least two countries and go beyond national borders.",
      "Affect only one government ministry's internal operations",
      "Last less than twenty-four hours from start to finish",
    ],
    a: 1,
  },
  {
    n: 36,
    t: "Emergency classification",
    q: "Which natural disasters are classified as Geophysical emergencies?",
    o: [
      "Epidemics and epizootic disease outbreaks among populations",
      "Economic crises and mass riots across regions",
      "Earthquakes and volcanic eruptions.",
      "Industrial chemical plant accidents and leaks",
    ],
    a: 2,
  },
  {
    n: 37,
    t: "Emergency classification",
    q: "Epiphytotics are the rapid spread of infectious diseases among:",
    o: ["Plants.", "Animals.", "Humans.", "Insects."],
    a: 0,
  },
  {
    n: 38,
    t: "Emergency classification",
    q: "Which of the following is a Technogenic disaster?",
    o: [
      "Earthquakes and volcanic eruption events that occur within a given natural region",
      "Mass riots and a sudden financial market collapse spreading across a country",
      "Seasonal drought and widespread crop failure events affecting rural agriculture",
      "Industrial and man-made accidents (building collapse, nuclear accidents, chemical releases, transport accidents).",
    ],
    a: 3,
  },
  {
    n: 39,
    t: "Emergency classification",
    q: "Economic crises, financial collapse, and mass riots are examples of:",
    o: [
      "Geophysical emergencies.",
      "Socio-economic emergencies.",
      "Hydrological emergencies.",
      "Technogenic emergencies.",
    ],
    a: 1,
  },
  {
    n: 40,
    t: "Warning systems & signals",
    q: 'What is the purpose of the sound signal "Attention everyone!"?',
    o: [
      "To announce the start of a national public holiday",
      "To signal the formal end of a scheduled drill",
      "To attract attention and warn the population about danger.",
      "To call factory workers back from a lunch break",
    ],
    a: 2,
  },
  {
    n: 41,
    t: "Warning systems & signals",
    q: "What should people immediately do after hearing the signal?",
    o: [
      "Turn on radio and television and follow official instructions.",
      "Immediately leave their homes and run outside at once",
      "Call neighbors first to confirm what they just heard",
      "Wait quietly indoors for a follow-up text message",
    ],
    a: 0,
  },
  {
    n: 42,
    t: "Warning systems & signals",
    q: "What is the main advantage of the Cell Broadcast System?",
    o: [
      "It requires no electricity at all to function properly",
      "It only works for older landline telephone users",
      "It sends out alert messages once a week as scheduled",
      "Instant delivery to all phones in a geographic area regardless of network load.",
    ],
    a: 3,
  },
  {
    n: 43,
    t: "Warning systems & signals",
    q: "Which warning method sends standard SMS based on mobile operator location data?",
    o: [
      "Cell Broadcast System.",
      "Location-Based SMS (LB-SMS).",
      "The S-40 electric siren.",
      "Ground reconnaissance reporting.",
    ],
    a: 1,
  },
  {
    n: 44,
    t: "Warning systems & signals",
    q: "Where is the S-40 electric siren installed and how far is it heard?",
    o: [
      "Installed inside factories; audible only a few meters",
      "Installed on rooftops only; audible within 50 meters",
      "Installed on streets; audible from 300–700 meters.",
      "Installed in tunnels; audible up to 5 kilometers",
    ],
    a: 2,
  },
  {
    n: 45,
    t: "Warning systems & signals",
    q: "What is the S-28 siren designed for?",
    o: [
      "Noisy industrial workshops.",
      "Open rural farmland areas.",
      "Quiet residential bedrooms.",
      "Underwater coastal stations.",
    ],
    a: 0,
  },
  {
    n: 46,
    t: "Neutron weapons",
    q: "What is the primary destructive effect of a neutron weapon based on?",
    o: [
      "Pure thermal blast energy.",
      "Electromagnetic pulse alone.",
      "Conventional shrapnel fragments.",
      "Penetrating neutron radiation.",
    ],
    a: 3,
  },
  {
    n: 47,
    t: "Neutron weapons",
    q: "How does the radiation power of a neutron weapon compare to conventional nuclear weapons?",
    o: [
      "It is roughly equal in every measurable respect",
      "Radiation power is 5–6 times higher; radiation area is about twice as large.",
      "It produces essentially no radiation effect at all",
      "Radiation power is actually much lower overall",
    ],
    a: 1,
  },
  {
    n: 48,
    t: "Nuclear weapons & effects",
    q: "When and where did the United States first use nuclear weapons?",
    o: [
      "1942, Pearl Harbor area.",
      "1949, the Nevada desert.",
      "1945, Hiroshima and Nagasaki.",
      "1955, the Bikini Atoll.",
    ],
    a: 2,
  },
  {
    n: 49,
    t: "Nuclear weapons & effects",
    q: "What characterizes the explosive power of nuclear ammunition?",
    o: [
      "TNT equivalent (tons, kilotons, megatons).",
      "Standard caliber measured in millimeters of width",
      "Total weight measured strictly in metric tons",
      "Burn duration measured precisely in seconds",
    ],
    a: 0,
  },
  {
    n: 50,
    t: "Nuclear weapons & effects",
    q: "Which nuclear reactions form the basis of nuclear weapons?",
    o: [
      "Oxidation and combustion chemical reactions",
      "Electrolysis and ionization chemical reactions",
      "Polymerization and catalysis chemical reactions",
      "Fission and fusion reactions.",
    ],
    a: 3,
  },
  {
    n: 51,
    t: "Nuclear weapons & effects",
    q: "What happens during a fission reaction?",
    o: [
      "Light nuclei merge together releasing modest energy",
      "Heavy atoms split into lighter nuclei releasing large energy.",
      "Atoms remain entirely unchanged in their structure",
      "Electrons are simply stripped from stable atoms",
    ],
    a: 1,
  },
  {
    n: 52,
    t: "Nuclear weapons & effects",
    q: "How many damaging factors does a nuclear explosion have?",
    o: ["Three.", "Seven.", "Five.", "Nine."],
    a: 2,
  },
  {
    n: 53,
    t: "Nuclear weapons & effects",
    q: "What percentage of energy is spent on the shockwave?",
    o: ["About 50%.", "About 20%.", "About 70%.", "About 90%."],
    a: 0,
  },
  {
    n: 54,
    t: "Nuclear weapons & effects",
    q: "What percentage of energy is spent on light radiation?",
    o: ["About 10%.", "About 60%.", "About 80%.", "About 35%."],
    a: 3,
  },
  {
    n: 55,
    t: "Nuclear weapons & effects",
    q: "What are the two main destructive effects of light radiation?",
    o: [
      "Sound damage and ground tremors across wide areas",
      "Burns and blindness; mass fires.",
      "Frost damage and ice formation on surfaces nearby",
      "Static discharge and signal loss in electronics",
    ],
    a: 1,
  },
  {
    n: 56,
    t: "Nuclear weapons & effects",
    q: "Which components constitute penetrating radiation?",
    o: [
      "Alpha particles and fine dust particles only",
      "Ultraviolet light and infrared light waves",
      "Gamma rays and neutron streams.",
      "Static electricity and small visible sparks",
    ],
    a: 2,
  },
  {
    n: 57,
    t: "Nuclear weapons & effects",
    q: "What is the condition at radiation dose D = 400–600 rad (4–6 Gy)?",
    o: [
      "III degree severe radiation sickness.",
      "I degree mild radiation sickness.",
      "No measurable health effect at all.",
      "Full immediate recovery is expected.",
    ],
    a: 0,
  },
  {
    n: 58,
    t: "Nuclear weapons & effects",
    q: "What is the condition at radiation dose D = 200–400 rad (2–4 Gy)?",
    o: [
      "No symptoms whatsoever appear.",
      "IV degree fatal radiation sickness.",
      "Mild seasonal allergy symptoms only.",
      "II degree moderate radiation sickness.",
    ],
    a: 3,
  },
  {
    n: 59,
    t: "Chemical weapons",
    q: "What is the core component of chemical weapons?",
    o: [
      "Radioactive isotope cores.",
      "Toxic substances.",
      "Compressed inert gases.",
      "High-explosive charges only.",
    ],
    a: 1,
  },
  {
    n: 60,
    t: "Chemical weapons",
    q: "According to tactical purpose, chemical weapons are divided into which two types?",
    o: [
      "Solid and liquid chemical weapon types",
      "Domestic and imported chemical weapon types",
      "Lethal and incapacitating chemical weapons.",
      "Civilian and industrial chemical weapon types",
    ],
    a: 2,
  },
  {
    n: 61,
    t: "Chemical weapons",
    q: "Substances whose effect lasts for minutes are called:",
    o: [
      "Volatile (unstable) substances.",
      "Persistent (stable) substances.",
      "Radioactive (decaying) substances.",
      "Inert (neutral) substances.",
    ],
    a: 0,
  },
  {
    n: 62,
    t: "Chemical weapons",
    q: "When did the Chemical Weapons Convention come into force?",
    o: [
      "January 1, 1968.",
      "October 8, 1985.",
      "November 13, 1997.",
      "March 26, 1972.",
    ],
    a: 3,
  },
  {
    n: 63,
    t: "Chemical weapons",
    q: "Which hazardous chemical is a yellow-green gas heavier than air causing pulmonary edema?",
    o: ["Ammonia.", "Chlorine.", "Hydrogen sulfide.", "Carbon dioxide."],
    a: 1,
  },
  {
    n: 64,
    t: "Chemical weapons",
    q: "Which hazardous chemical is a colorless liquid with bitter almond odor?",
    o: [
      "Sulfuric acid.",
      "Hydrochloric acid.",
      "Hydrocyanic acid.",
      "Phosphoric acid.",
    ],
    a: 2,
  },
  {
    n: 65,
    t: "Chemical weapons",
    q: "What is the Primary Zone of chemical contamination?",
    o: [
      "Area directly affected by the toxic substance.",
      "Area where toxic vapors and aerosols spread further",
      "Area entirely outside the contamination range zone",
      "Area reserved exclusively for medical staff only",
    ],
    a: 0,
  },
  {
    n: 66,
    t: "Chemical weapons",
    q: "What is the Secondary Zone of chemical contamination?",
    o: [
      "Area directly affected by the toxic substance itself",
      "Area reserved exclusively for decontamination work",
      "Area where the chemical agent originally was stored",
      "Area where toxic vapors and aerosols spread.",
    ],
    a: 3,
  },
  {
    n: 67,
    t: "Chemical weapons",
    q: "What is the function of the Individual Chemical Package (ICP)?",
    o: [
      "Long-term storage of collected chemical samples",
      "Immediate decontamination of skin and clothing.",
      "Transport of hazardous waste materials offsite",
      "Calibration of field detection instruments only",
    ],
    a: 1,
  },
  {
    n: 68,
    t: "Chemical weapons",
    q: "What is cleaning contaminated areas with special solutions called?",
    o: [
      "Disinfection.",
      "Deratization.",
      "Degassing (decontamination).",
      "Sterilization procedure.",
    ],
    a: 2,
  },
  {
    n: 69,
    t: "Chemical weapons",
    q: "What is the crucial immediate first aid step for chemical contamination?",
    o: [
      "Put on a gas mask and evacuate to fresh air.",
      "Apply a tourniquet to the nearest available limb",
      "Administer CPR regardless of observed symptoms",
      "Wait indoors calmly for an ambulance to arrive",
    ],
    a: 0,
  },
  {
    n: 70,
    t: "Biosafety & biosecurity",
    q: "What is the goal of Biosafety?",
    o: [
      "Prevent unauthorized access to pathogens entirely",
      "Increase pathogen production for research purposes",
      "Track pathogen sales across international borders",
      "Protect people from accidental exposure to pathogens.",
    ],
    a: 3,
  },
  {
    n: 71,
    t: "Biosafety & biosecurity",
    q: "What is the goal of Biosecurity?",
    o: [
      "Protect people from accidental pathogen exposure",
      "Prevent unauthorized access to pathogens.",
      "Reduce laboratory equipment maintenance costs",
      "Speed up pathogen sample shipping times overall",
    ],
    a: 1,
  },
  {
    n: 72,
    t: "Population protection regulations",
    q: "Which document regulates population protection during emergencies in Azerbaijan?",
    o: [
      "“General Rules of Municipal Construction Safety and Building Permit Standards in Urban Districts”.",
      "“National Framework for Industrial Trade Tariffs and Customs Regulations Between Member States”.",
      "“Main Principles of Population Protection in Emergency Situations during Peacetime and Wartime in the Republic of Azerbaijan”.",
      "“Standard Code of Public Transportation Conduct and Passenger Safety Rules Nationwide”.",
    ],
    a: 2,
  },
  {
    n: 73,
    t: "Population protection regulations",
    q: "According to which principle is the scale of population protection measures carried out?",
    o: [
      "Purposeful and sufficient principle.",
      "Maximum and unrestricted protection principle",
      "Random and proportional protection principle",
      "Minimal and delayed protection principle",
    ],
    a: 0,
  },
  {
    n: 74,
    t: "Population protection regulations",
    q: "Which body approved the Regulation on Population Evacuation on August 6, 1993?",
    o: [
      "The Milli Majlis legislative body of Azerbaijan",
      "The Ministry of Internal Affairs of Azerbaijan",
      "The Supreme Court of the Republic of Azerbaijan",
      "Cabinet of Ministers of the Republic of Azerbaijan.",
    ],
    a: 3,
  },
  {
    n: 75,
    t: "Population protection regulations",
    q: "What is the definition of Evacuation (relocation)?",
    o: [
      "Permanent resettlement of an entire nation's population",
      "Organized removal of people from dangerous areas to safe areas.",
      "Temporary closure of a single local business",
      "Voluntary travel undertaken for tourism purposes",
    ],
    a: 1,
  },
  {
    n: 76,
    t: "Population protection regulations",
    q: "When should evacuation be carried out during emergencies?",
    o: [
      "Only after all casualties have been fully confirmed",
      "Strictly within official government business hours",
      "In advance or immediately after danger begins.",
      "Only once media coverage of the event has started",
    ],
    a: 2,
  },
  {
    n: 77,
    t: "Population protection regulations",
    q: "Who issues evacuation orders during floods?",
    o: [
      "Emergency Commission.",
      "Local weather bureau.",
      "Municipal tax office.",
      "Regional transport authority.",
    ],
    a: 0,
  },
  {
    n: 78,
    t: "Population protection regulations",
    q: "When should evacuation occur during chemical or radioactive accidents?",
    o: [
      "Only after symptoms appear among nearby residents",
      "Exactly twenty-four hours after the accident occurs",
      "Once cleanup crews finish their assigned work",
      "Before toxic clouds or radiation reach the population.",
    ],
    a: 3,
  },
  {
    n: 79,
    t: "Personal & collective protection",
    q: "Individual Protection Equipment protects against which hazards?",
    o: [
      "Only minor weather-related discomfort and exposure",
      "Chemical, biological, radiological hazards and harmful effects.",
      "Workplace noise and poor lighting conditions",
      "Routine traffic and daily commuting risks",
    ],
    a: 1,
  },
  {
    n: 80,
    t: "Personal & collective protection",
    q: "How do filter gas masks protect the respiratory system?",
    o: [
      "By supplying pure compressed oxygen only to the wearer",
      "By sealing the mouth completely shut at all times",
      "By filtering harmful substances from inhaled air.",
      "By cooling all inhaled air to a very low temperature",
    ],
    a: 2,
  },
  {
    n: 81,
    t: "Personal & collective protection",
    q: "What footwear is included in B-level protection suits?",
    o: [
      "Long rubber boots with steel toes.",
      "Lightweight canvas sneakers.",
      "Open-toed leather sandals.",
      "Standard cloth slip-on shoes.",
    ],
    a: 0,
  },
  {
    n: 82,
    t: "Personal & collective protection",
    q: "D-level protection is intended for which scenario?",
    o: [
      "High-altitude aviation operations and flight crews",
      "Deep-sea underwater diving missions and salvage",
      "Long-duration space travel activities and missions",
      "Emergency rescue and routine work tasks.",
    ],
    a: 3,
  },
  {
    n: 83,
    t: "Personal & collective protection",
    q: "By location, collective protection facilities are classified as:",
    o: [
      "Indoor and outdoor.",
      "Attached and separate.",
      "Urban and rural.",
      "Public and private.",
    ],
    a: 1,
  },
  {
    n: 84,
    t: "Personal & collective protection",
    q: "By construction period, collective protection facilities are classified as:",
    o: [
      "Temporary and permanent.",
      "Funded and unfunded.",
      "Pre-built and quickly constructed.",
      "Inspected and uninspected.",
    ],
    a: 2,
  },
  {
    n: 85,
    t: "Personal & collective protection",
    q: "Which collective protection structure protects against all harmful effects?",
    o: ["Shelter.", "Open trench.", "Storage shed.", "Watchtower."],
    a: 0,
  },
  {
    n: 86,
    t: "Personal & collective protection",
    q: "Radiation Protection Bunkers protect against which two factors?",
    o: [
      "Heat and humidity level factors",
      "Noise and vibration impact factors",
      "Wind and rainfall exposure factors",
      "Radiation and shock wave.",
    ],
    a: 3,
  },
  {
    n: 87,
    t: "Rescue and recovery stages",
    q: "Stage I of Rescue and Emergency Works is called:",
    o: [
      "Final Assessment.",
      "Initial Measures.",
      "Long-Term Planning.",
      "Budget Allocation.",
    ],
    a: 1,
  },
  {
    n: 88,
    t: "Rescue and recovery stages",
    q: "Stage II of Rescue and Emergency Works focuses on:",
    o: [
      "Initial scene assessment and reporting only",
      "Long-term legislative reform and review",
      "Elimination of emergency consequences.",
      "International donor coordination efforts",
    ],
    a: 2,
  },
  {
    n: 89,
    t: "Rescue and recovery stages",
    q: "Stage III of Rescue and Emergency Works is called:",
    o: [
      "Restoration of normal life activities.",
      "Preliminary danger identification across the zone",
      "Initial victim count reporting to headquarters",
      "Equipment inventory checking before deployment",
    ],
    a: 0,
  },
  {
    n: 90,
    t: "Rescue and recovery stages",
    q: "The return of evacuated people is carried out during:",
    o: ["Stage I.", "Stage II.", "A separate fourth stage.", "Stage III."],
    a: 3,
  },
  {
    n: 91,
    t: "Reconnaissance methods",
    q: "What is the main goal of civil defense reconnaissance?",
    o: [
      "Generate extra revenue for emergency services overall",
      "Collect accurate information for decision-making and population protection.",
      "Train new recruits only in basic hand-to-hand combat",
      "Document historical disaster statistics for archives",
    ],
    a: 1,
  },
  {
    n: 92,
    t: "Reconnaissance methods",
    q: "What is a primary task of reconnaissance during peacetime?",
    o: [
      "Negotiating international trade agreements abroad",
      "Managing public transportation schedules locally",
      "Monitoring environmental contamination and epidemic situation.",
      "Reviewing annual government budget reports",
    ],
    a: 2,
  },
  {
    n: 93,
    t: "Reconnaissance methods",
    q: "Which reconnaissance type is the most precise and comprehensive?",
    o: [
      "Ground reconnaissance.",
      "Aerial reconnaissance.",
      "Satellite reconnaissance.",
      "Naval reconnaissance.",
    ],
    a: 0,
  },
  {
    n: 94,
    t: "Reconnaissance methods",
    q: "Which reconnaissance type is carried out by aircraft or helicopters?",
    o: [
      "Ground reconnaissance.",
      "Underwater reconnaissance.",
      "Foot patrol reconnaissance.",
      "Aerial reconnaissance.",
    ],
    a: 3,
  },
  {
    n: 95,
    t: "Emergency first aid basics",
    q: "In cardiac and respiratory arrest, life depends on first aid during:",
    o: [
      "The first several hours.",
      "The first few minutes.",
      "The first full day.",
      "The first entire week.",
    ],
    a: 1,
  },
  {
    n: 96,
    t: "Emergency first aid basics",
    q: 'In the DRCABD algorithm, "D" stands for:',
    o: ["Diagnosis.", "Defibrillation.", "Danger.", "Dislocation."],
    a: 2,
  },
  {
    n: 97,
    t: "Emergency first aid basics",
    q: 'What is done in the "R – Response" step?',
    o: [
      "Check victim’s responsiveness.",
      "Apply a tourniquet immediately to the wound",
      "Begin chest compressions at once without checking",
      "Record the time of the incident for the report",
    ],
    a: 0,
  },
  {
    n: 98,
    t: "Emergency first aid basics",
    q: "What is the CPR compression-to-breath ratio?",
    o: ["15:1.", "10:5.", "20:4.", "30:2."],
    a: 3,
  },
  {
    n: 99,
    t: "Emergency first aid basics",
    q: "Which type of bleeding is fast, under pressure, and bright red?",
    o: [
      "Venous bleeding.",
      "Arterial bleeding.",
      "Capillary bleeding.",
      "Internal bleeding.",
    ],
    a: 1,
  },
  {
    n: 100,
    t: "Emergency first aid basics",
    q: "Which type of bleeding is slow, common, and clots easily?",
    o: [
      "Arterial bleeding.",
      "Venous bleeding.",
      "Capillary bleeding.",
      "Parenchymal bleeding.",
    ],
    a: 2,
  },
];

export const TOPIC_ORDER = [
  "Foundations of civil defense",
  "State Emergency System structure",
  "Commissions & headquarters",
  "Planning, exercises & training",
  "Emergency classification",
  "Warning systems & signals",
  "Neutron weapons",
  "Nuclear weapons & effects",
  "Chemical weapons",
  "Biosafety & biosecurity",
  "Population protection regulations",
  "Personal & collective protection",
  "Rescue and recovery stages",
  "Reconnaissance methods",
  "Emergency first aid basics",
];
